const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Turret,
		C3.Behaviors.Pathfinding,
		C3.Behaviors.MoveTo,
		C3.Behaviors.LOS,
		C3.Behaviors.jumpthru,
		C3.Plugins.Touch,
		C3.Behaviors.DragnDrop,
		C3.Plugins.Text,
		C3.Plugins.TiledBg,
		C3.Behaviors.Bullet,
		C3.Behaviors.bound,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pathfinding.Acts.AddObstacle,
		C3.Behaviors.MoveTo.Acts.MoveAlongPathfindingPath,
		C3.Behaviors.Turret.Acts.AcquireTarget,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Pathfinding.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Pathfinding.Acts.FindPath,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.Turret.Acts.AddTarget,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.ChangeTags,
		C3.Plugins.Sprite.Cnds.HasTags,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.LOS.Cnds.HasLOSToObject,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Behaviors.Pathfinding.Cnds.OnPathFound,
		C3.Behaviors.Pathfinding.Acts.StartMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Touch.Cnds.OnTapGestureObject
	];
};
self.C3_JsPropNameTable = [
	{Solid: 0},
	{Turret: 0},
	{TowerBlue: 0},
	{towerblue2: 0},
	{line: 0},
	{towerred: 0},
	{towered2: 0},
	{Pathfinding: 0},
	{waterbtw: 0},
	{Barbhp: 0},
	{Team: 0},
	{MoveTo: 0},
	{LineOfSight: 0},
	{Jumpthru: 0},
	{barblue: 0},
	{ignore: 0},
	{Touch: 0},
	{DragDrop: 0},
	{barbcardblue: 0},
	{Text: 0},
	{Text2: 0},
	{Spookertron: 0},
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{SPROOGred: 0},
	{Sproogb: 0},
	{Barbcardred: 0},
	{Elixred: 0},
	{Bullet: 0},
	{rwtheg: 0},
	{barbhp: 0},
	{BoundToLayout: 0},
	{barbred: 0},
	{Invisblue: 0},
	{GOBLINHP: 0},
	{DAMAGE: 0},
	{GOBLUE: 0},
	{GOBLINCARD: 0},
	{Spear: 0},
	{BlueGoblinTarget: 0},
	{Redgoblincrad: 0},
	{Hp: 0},
	{Redgoblin: 0},
	{Redgoblintarget: 0},
	{Bs1: 0},
	{Bs2: 0},
	{Rs2: 0},
	{Rs1: 0},
	{bsI: 0},
	{Text3: 0},
	{Text4: 0},
	{TiledBackground3: 0},
	{clotyu: 0},
	{Sprite: 0},
	{Mouse: 0},
	{Jill: 0},
	{Blue: 0},
	{Cards: 0},
	{red: 0},
	{ismove: 0},
	{towertarget_Y: 0},
	{towertarget_X: 0},
	{Hpenemy: 0},
	{Iframe: 0},
	{ElixBLUE: 0},
	{Redtowerdamage: 0},
	{Bluehp: 0},
	{Blueteamhp: 0},
	{Bluedps: 0},
	{Gbif: 0},
	{bs1: 0}
];

self.InstanceType = {
	TowerBlue: class extends self.ISpriteInstance {},
	towerblue2: class extends self.ISpriteInstance {},
	line: class extends self.ISpriteInstance {},
	towerred: class extends self.ISpriteInstance {},
	towered2: class extends self.ISpriteInstance {},
	waterbtw: class extends self.ISpriteInstance {},
	barblue: class extends self.ISpriteInstance {},
	ignore: class extends self.ISpriteInstance {},
	Touch: class extends self.IInstance {},
	barbcardblue: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	Text2: class extends self.ITextInstance {},
	Spookertron: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	SPROOGred: class extends self.ISpriteInstance {},
	Sproogb: class extends self.ISpriteInstance {},
	Barbcardred: class extends self.ISpriteInstance {},
	Elixred: class extends self.ITextInstance {},
	Bullet: class extends self.ISpriteInstance {},
	rwtheg: class extends self.ITextInstance {},
	barbred: class extends self.ISpriteInstance {},
	Invisblue: class extends self.ISpriteInstance {},
	GOBLUE: class extends self.ISpriteInstance {},
	GOBLINCARD: class extends self.ISpriteInstance {},
	Spear: class extends self.ISpriteInstance {},
	BlueGoblinTarget: class extends self.ISpriteInstance {},
	Redgoblincrad: class extends self.ISpriteInstance {},
	Redgoblin: class extends self.ISpriteInstance {},
	Redgoblintarget: class extends self.ISpriteInstance {},
	Bs1: class extends self.ISpriteInstance {},
	Bs2: class extends self.ISpriteInstance {},
	Rs2: class extends self.ISpriteInstance {},
	Rs1: class extends self.ISpriteInstance {},
	bsI: class extends self.ITextInstance {},
	Text3: class extends self.ITextInstance {},
	Text4: class extends self.ITextInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	clotyu: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Jill: class extends self.ISpriteInstance {},
	Blue: class extends self.ISpriteInstance {},
	Cards: class extends self.ISpriteInstance {},
	red: class extends self.ISpriteInstance {}
}